# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.cache/wt [current_project]
set_property parent.project_path C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/Macro.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/ACC.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/ALU.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/CPU.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/PC.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/CPU_top.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/MAR.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/MBR.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/Memory.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/IR.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/CS.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/ControlUnit.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/BR.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/binary_to_BCD.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/clock_all.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/scan_seg.v
  C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/sources_1/new/key_test.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/constrs_1/new/top_constrs.xdc
set_property used_in_implementation false [get_files C:/Users/lab/Desktop/CPU_new/CPU_zfzdr/CPU_zfzdr.srcs/constrs_1/new/top_constrs.xdc]


synth_design -top CPU_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef CPU_top.dcp

catch { report_utilization -file CPU_top_utilization_synth.rpt -pb CPU_top_utilization_synth.pb }
